export const ACTION_ACCOUNT_SET_LOADING = "ACTION_ACCOUNT_SET_LOADING";
export const ACTION_ACCOUNT_SET_ERROR = "ACTION_ACCOUNT_SET_ERROR";
export const ACTION_ACCOUNT_SET_ACCOUNTS = "ACTION_ACCOUNT_SET_ACCOUNTS";
export const ACTION_ACCOUNT_SELECT = "ACTION_ACCOUNT_SELECT";
export const ACTION_ACCOUNT_SET_ACTIVE_STATES =
  "ACTION_ACCOUNT_SET_ACTIVE_STATES";
export const ACTION_ACCOUNT_DELETE_ID = "ACTION_ACCOUNT_DELETE_ID";
